name: Import Supabase Dev DB

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Show GitHub runner public IP
        run: curl https://ifconfig.me

      - name: Print connection details (excluding password)
        run: |
          echo "Connecting to host: ${{ secrets.SUPABASE_HOST }}"
          echo "Database: ${{ secrets.SUPABASE_DB }}"
          echo "User: ${{ secrets.SUPABASE_USER }}"
          echo "File: prod_dump.sql"

      - name: Test connection
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: |
          echo "Testing connection to Supabase..."
          psql \
            -h ${{ secrets.SUPABASE_HOST }} \
            -U ${{ secrets.SUPABASE_USER }} \
            -d ${{ secrets.SUPABASE_DB }} \
            -c '\conninfo'

      - name: Import prod_dump.sql into Supabase Dev
        if: ${{ success() }}
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: |
          echo "Starting import..."
          psql \
            -h ${{ secrets.SUPABASE_HOST }} \
            -U ${{ secrets.SUPABASE_USER }} \
            -d ${{ secrets.SUPABASE_DB }} \
            -f prod_dump.sql
