name: Import Supabase Dev DB

on:
  workflow_dispatch:  # Manual trigger

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Import prod_dump.sql into Supabase Dev
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
        run: |
          echo "Starting import into Supabase dev DB..."
          psql \
            -h ${{ secrets.SUPABASE_HOST }} \
            -U ${{ secrets.SUPABASE_USER }} \
            -d ${{ secrets.SUPABASE_DB }} \
            -f prod_dump.sql
